import React from "react";
import ScoreBoard from "./ScoreBoard/ScoreBoard";
import classes from "./ScoreBoards.module.css";
import PlayerList1 from "./PlayerList/PlayerList1";
import PlayerList2 from "./PlayerList/PlayerList2";
import PlayerList3 from "./PlayerList/PlayerList3";
import PlayerList4 from "./PlayerList/PlayerList4";

const scoreBoards = (props) => {
  let PlayerLists = [];

  if (props.numOfPlayers === 2) {
    PlayerLists = [
      <PlayerList1
        key={1}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        totalScore={props.totalScore}
        playerOneOneSum={props.playerOneOneSum}
        playerOneTwoSum={props.playerOneTwoSum}
        playerOneThreeSum={props.playerOneThreeSum}
        playerOneFourSum={props.playerOneFourSum}
        playerOneFiveSum={props.playerOneFiveSum}
        playerOneSixSum={props.playerOneSixSum}
        playerOneBonusSum={props.playerOneBonusSum}
        playerOneBonusRes={props.playerOneBonusRes}
        playerOnePairSum={props.playerOnePairSum}
        playerOneTwoPairSum={props.playerOneTwoPairSum}
        playerOneThreeOfAKindSum={props.playerOneThreeOfAKindSum}
        playerOneFourOfAKindSum={props.playerOneFourOfAKindSum}
        playerOneSmallStraightSum={props.playerOneSmallStraightSum}
        playerOneBigStraightSum={props.playerOneBigStraightSum}
        playerOneFullHouseSum={props.playerOneFullHouseSum}
        playerOneChanceSum={props.playerOneChanceSum}
        playerOneYatzeSum={props.playerOneYatzeSum}
        playerOneTotalScoreSum={props.playerOneTotalScoreSum}
      />,
      <PlayerList2
        key={2}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        totalScore={props.totalScore}
        playerTwoOneSum={props.playerTwoOneSum}
        playerTwoTwoSum={props.playerTwoTwoSum}
        playerTwoThreeSum={props.playerTwoThreeSum}
        playerTwoFourSum={props.playerTwoFourSum}
        playerTwoFiveSum={props.playerTwoFiveSum}
        playerTwoSixSum={props.playerTwoSixSum}
        playerTwoBonusSum={props.playerTwoBonusSum}
        playerTwoBonusRes={props.playerTwoBonusRes}
        playerTwoPairSum={props.playerTwoPairSum}
        playerTwoTwoPairSum={props.playerTwoTwoPairSum}
        playerTwoThreeOfAKindSum={props.playerTwoThreeOfAKindSum}
        playerTwoFourOfAKindSum={props.playerTwoFourOfAKindSum}
        playerTwoSmallStraightSum={props.playerTwoSmallStraightSum}
        playerTwoBigStraightSum={props.playerTwoBigStraightSum}
        playerTwoFullHouseSum={props.playerTwoFullHouseSum}
        playerTwoChanceSum={props.playerTwoChanceSum}
        playerTwoYatzeSum={props.playerTwoYatzeSum}
        playerTwoTotalScoreSum={props.playerTwoTotalScoreSum}
      />,
    ];
  } else if (props.numOfPlayers === 3) {
    PlayerLists = [
      <PlayerList1
        key={1}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        totalScore={props.totalScore}
        playerOneOneSum={props.playerOneOneSum}
        playerOneTwoSum={props.playerOneTwoSum}
        playerOneThreeSum={props.playerOneThreeSum}
        playerOneFourSum={props.playerOneFourSum}
        playerOneFiveSum={props.playerOneFiveSum}
        playerOneSixSum={props.playerOneSixSum}
        playerOneBonusSum={props.playerOneBonusSum}
        playerOneBonusRes={props.playerOneBonusRes}
        playerOnePairSum={props.playerOnePairSum}
        playerOneTwoPairSum={props.playerOneTwoPairSum}
        playerOneThreeOfAKindSum={props.playerOneThreeOfAKindSum}
        playerOneFourOfAKindSum={props.playerOneFourOfAKindSum}
        playerOneSmallStraightSum={props.playerOneSmallStraightSum}
        playerOneBigStraightSum={props.playerOneBigStraightSum}
        playerOneFullHouseSum={props.playerOneFullHouseSum}
        playerOneChanceSum={props.playerOneChanceSum}
        playerOneYatzeSum={props.playerOneYatzeSum}
        playerOneTotalScoreSum={props.playerOneTotalScoreSum}
      />,
      <PlayerList2
        key={2}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        totalScore={props.totalScore}
        playerTwoOneSum={props.playerTwoOneSum}
        playerTwoTwoSum={props.playerTwoTwoSum}
        playerTwoThreeSum={props.playerTwoThreeSum}
        playerTwoFourSum={props.playerTwoFourSum}
        playerTwoFiveSum={props.playerTwoFiveSum}
        playerTwoSixSum={props.playerTwoSixSum}
        playerTwoBonusSum={props.playerTwoBonusSum}
        playerTwoBonusRes={props.playerTwoBonusRes}
        playerTwoPairSum={props.playerTwoPairSum}
        playerTwoTwoPairSum={props.playerTwoTwoPairSum}
        playerTwoThreeOfAKindSum={props.playerTwoThreeOfAKindSum}
        playerTwoFourOfAKindSum={props.playerTwoFourOfAKindSum}
        playerTwoSmallStraightSum={props.playerTwoSmallStraightSum}
        playerTwoBigStraightSum={props.playerTwoBigStraightSum}
        playerTwoFullHouseSum={props.playerTwoFullHouseSum}
        playerTwoChanceSum={props.playerTwoChanceSum}
        playerTwoYatzeSum={props.playerTwoYatzeSum}
        playerTwoTotalScoreSum={props.playerTwoTotalScoreSum}
      />,
      <PlayerList3
        key={3}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        totalScore={props.totalScore}
        playerThreeOneSum={props.playerThreeOneSum}
        playerThreeTwoSum={props.playerThreeTwoSum}
        playerThreeThreeSum={props.playerThreeThreeSum}
        playerThreeFourSum={props.playerThreeFourSum}
        playerThreeFiveSum={props.playerThreeFiveSum}
        playerThreeSixSum={props.playerThreeSixSum}
        playerThreeBonusSum={props.playerThreeBonusSum}
        playerThreeBonusRes={props.playerThreeBonusRes}
        playerThreePairSum={props.playerThreePairSum}
        playerThreeTwoPairSum={props.playerThreeTwoPairSum}
        playerThreeThreeOfAKindSum={props.playerThreeThreeOfAKindSum}
        playerThreeFourOfAKindSum={props.playerThreeFourOfAKindSum}
        playerThreeSmallStraightSum={props.playerThreeSmallStraightSum}
        playerThreeBigStraightSum={props.playerThreeBigStraightSum}
        playerThreeFullHouseSum={props.playerThreeFullHouseSum}
        playerThreeChanceSum={props.playerThreeChanceSum}
        playerThreeYatzeSum={props.playerThreeYatzeSum}
        playerThreeTotalScoreSum={props.playerThreeTotalScoreSum}
      />,
    ];
  } else if (props.numOfPlayers === 4) {
    PlayerLists = [
      <PlayerList1
        key={1}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        totalScore={props.totalScore}
        playerOneOneSum={props.playerOneOneSum}
        playerOneTwoSum={props.playerOneTwoSum}
        playerOneThreeSum={props.playerOneThreeSum}
        playerOneFourSum={props.playerOneFourSum}
        playerOneFiveSum={props.playerOneFiveSum}
        playerOneSixSum={props.playerOneSixSum}
        playerOneBonusSum={props.playerOneBonusSum}
        playerOneBonusRes={props.playerOneBonusRes}
        playerOnePairSum={props.playerOnePairSum}
        playerOneTwoPairSum={props.playerOneTwoPairSum}
        playerOneThreeOfAKindSum={props.playerOneThreeOfAKindSum}
        playerOneFourOfAKindSum={props.playerOneFourOfAKindSum}
        playerOneSmallStraightSum={props.playerOneSmallStraightSum}
        playerOneBigStraightSum={props.playerOneBigStraightSum}
        playerOneFullHouseSum={props.playerOneFullHouseSum}
        playerOneChanceSum={props.playerOneChanceSum}
        playerOneYatzeSum={props.playerOneYatzeSum}
        playerOneTotalScoreSum={props.playerOneTotalScoreSum}
      />,
      <PlayerList2
        key={2}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        totalScore={props.totalScore}
        playerTwoOneSum={props.playerTwoOneSum}
        playerTwoTwoSum={props.playerTwoTwoSum}
        playerTwoThreeSum={props.playerTwoThreeSum}
        playerTwoFourSum={props.playerTwoFourSum}
        playerTwoFiveSum={props.playerTwoFiveSum}
        playerTwoSixSum={props.playerTwoSixSum}
        playerTwoBonusSum={props.playerTwoBonusSum}
        playerTwoBonusRes={props.playerTwoBonusRes}
        playerTwoPairSum={props.playerTwoPairSum}
        playerTwoTwoPairSum={props.playerTwoTwoPairSum}
        playerTwoThreeOfAKindSum={props.playerTwoThreeOfAKindSum}
        playerTwoFourOfAKindSum={props.playerTwoFourOfAKindSum}
        playerTwoSmallStraightSum={props.playerTwoSmallStraightSum}
        playerTwoBigStraightSum={props.playerTwoBigStraightSum}
        playerTwoFullHouseSum={props.playerTwoFullHouseSum}
        playerTwoChanceSum={props.playerTwoChanceSum}
        playerTwoYatzeSum={props.playerTwoYatzeSum}
        playerTwoTotalScoreSum={props.playerTwoTotalScoreSum}
      />,
      <PlayerList3
        key={3}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        totalScore={props.totalScore}
        playerThreeOneSum={props.playerThreeOneSum}
        playerThreeTwoSum={props.playerThreeTwoSum}
        playerThreeThreeSum={props.playerThreeThreeSum}
        playerThreeFourSum={props.playerThreeFourSum}
        playerThreeFiveSum={props.playerThreeFiveSum}
        playerThreeSixSum={props.playerThreeSixSum}
        playerThreeBonusSum={props.playerThreeBonusSum}
        playerThreeBonusRes={props.playerThreeBonusRes}
        playerThreePairSum={props.playerThreePairSum}
        playerThreeTwoPairSum={props.playerThreeTwoPairSum}
        playerThreeThreeOfAKindSum={props.playerThreeThreeOfAKindSum}
        playerThreeFourOfAKindSum={props.playerThreeFourOfAKindSum}
        playerThreeSmallStraightSum={props.playerThreeSmallStraightSum}
        playerThreeBigStraightSum={props.playerThreeBigStraightSum}
        playerThreeFullHouseSum={props.playerThreeFullHouseSum}
        playerThreeChanceSum={props.playerThreeChanceSum}
        playerThreeYatzeSum={props.playerThreeYatzeSum}
        playerThreeTotalScoreSum={props.playerThreeTotalScoreSum}
      />,
      <PlayerList4
        key={4}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        totalScore={props.totalScore}
        playerFourOneSum={props.playerFourOneSum}
        playerFourTwoSum={props.playerFourTwoSum}
        playerFourThreeSum={props.playerFourThreeSum}
        playerFourFourSum={props.playerFourFourSum}
        playerFourFiveSum={props.playerFourFiveSum}
        playerFourSixSum={props.playerFourSixSum}
        playerFourBonusSum={props.playerFourBonusSum}
        playerFourBonusRes={props.playerFourBonusRes}
        playerFourPairSum={props.playerFourPairSum}
        playerFourTwoPairSum={props.playerFourTwoPairSum}
        playerFourThreeOfAKindSum={props.playerFourThreeOfAKindSum}
        playerFourFourOfAKindSum={props.playerFourFourOfAKindSum}
        playerFourSmallStraightSum={props.playerFourSmallStraightSum}
        playerFourBigStraightSum={props.playerFourBigStraightSum}
        playerFourFullHouseSum={props.playerFourFullHouseSum}
        playerFourChanceSum={props.playerFourChanceSum}
        playerFourYatzeSum={props.playerFourYatzeSum}
        playerFourTotalScoreSum={props.playerFourTotalScoreSum}
      />,
    ];
  }

  return (
    <div className={classes.Row}>
      <ScoreBoard superYatzy={props.superYatzy} />
      {PlayerLists}
    </div>
  );

  /*let NumberOfPlayers = [];

  for (let i = 0; i < props.numOfPlayers; i++) {
    NumberOfPlayers.push(
      <PlayerList
        key={i}
        number={i + 1}
        ones={props.ones}
        twos={props.twos}
        threes={props.threes}
        fours={props.fours}
        fives={props.fives}
        sixes={props.sixes}
        bonus={props.bonus}
        bonusSumHandler={props.bonusSumHandler}
        pair={props.pair}
        twoPairs={props.twoPairs}
        threeOfAKind={props.threeOfAKind}
        fourOfAKind={props.fourOfAKind}
        smallStraight={props.smallStraight}
        bigStraight={props.bigStraight}
        fullHouse={props.fullHouse}
        chance={props.chance}
        yatze={props.yatze}
        onesSum={props.onesSum}
        twosSum={props.twosSum}
        threesSum={props.threesSum}
        foursSum={props.foursSum}
        fivesSum={props.fivesSum}
        sixesSum={props.sixesSum}
        bonusSum={props.bonusSum}
        bonusSumSum={props.bonusSumSum}
        pairSum={props.pairSum}
        twoPairsSum={props.twoPairsSum}
        threeOfAKindSum={props.threeOfAKindSum}
        fourOfAKindSum={props.fourOfAKindSum}
        smallStraightSum={props.smallStraightSum}
        bigStraightSum={props.bigStraightSum}
        chanceSum={props.chanceSum}
        yatzeSum={props.yatzeSum}
      />
    );
  }

  return (
    <div className={classes.Row}>
      <ScoreBoard />
      {NumberOfPlayers}
    </div>
  );*/
};

export default scoreBoards;
